### ISSUE TITLE
1+0=exception

### ISSUE THREAD

**Issue by fibonacci998** [pH-7/Simple-Java-Calculator#10]
I found error when click 1+0=

![screenshot 2018-05-03 17 00 46](https://user-images.githubusercontent.com/38557844/39570803-b90a4a02-4ef3-11e8-9fb6-3c3a30efc140.png)

**Comment by kwl3434** [comment]
add this line 
but[0].addActionListener(this);

**Comment by pH-7** [comment]
@fibonacci998 Do you mind to create a PR for it?

**Comment by pH-7** [comment]
@kwl3434 Very good! Do you mind to create a PR for it?

**Comment by pH-7** [comment]
> addActionListener



> add this line
> but[0].addActionListener(this);

 Do you mind to create a PR for it?

**Comment by pH-7** [comment]
> addActionListener



> add this line
> but[0].addActionListener(this);

 @kwl3434 Do you mind to create a PR for it?

**Comment by kwl3434** [comment]
@pH-7 Okey. Please, Just wait a day

**Comment by pH-7** [comment]
Super! Thank you @kwl3434! Really appreciate :)

**Comment by pH-7** [comment]
https://github.com/pH-7/Simple-Java-Calculator/pull/34

**Comment by pH-7** [comment]
> add this line
> but[0].addActionListener(this);

FYI @kwl3434 You mention adding`but[0].addActionListener(this); `, but your PR actually removes it https://github.com/pH-7/Simple-Java-Calculator/pull/34/files

**Comment by pH-7** [comment]
> > add this line
> > but[0].addActionListener(this);
> 
> FYI @kwl3434 You mention adding`but[0].addActionListener(this); `, but your PR actually removes it https://github.com/pH-7/Simple-Java-Calculator/pull/34/files

Do you mind to come back to this one @kwl3434 

See my comment here: https://github.com/pH-7/Simple-Java-Calculator/issues/10#issuecomment-623252062

**Comment by pH-7** [comment]
> > add this line
> > but[0].addActionListener(this);
> 
> FYI @kwl3434 You mention adding`but[0].addActionListener(this); `, but your PR actually removes it https://github.com/pH-7/Simple-Java-Calculator/pull/34/files

Do you mind to react to this one @kwl3434?

See my comment here: https://github.com/pH-7/Simple-Java-Calculator/issues/10#issuecomment-623252062
