### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [pH-7/Simple-Java-Calculator#14]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by pH-7** [comment]
That would be great @mansya 
Thanks for asking! Yeah, This "Simple Java Calculator" doesn't have a logo, and it would be great if you could design a nice one, and I will also add yourself in the list of contributors :)

Good luck :)

**Comment by pH-7** [comment]
And yes, of course, I will give you the most honest feedback about the logo. I know how it can help :)

**Comment by pH-7** [comment]
@mansya Any news? If you decided not to do it, that's completely fine, but please let me know and close this ticket. Thanks!

**Comment by mansya** [comment]
I have designed the logo for this project. are you interested ? if yes please tell which one you like. and if there are changes please inform me. 
![Calculator](https://user-images.githubusercontent.com/33461607/54447945-30fecd80-477d-11e9-8e91-4cae6fdd42f6.png)

sorry for a long time. I've been a little busy lately. but my busy life is over now.

**Comment by pH-7** [comment]
Hey @mansya 
Thanks of lot for them! 🎉 This is great!

The "2" looks the good one. However, would it be possible to have transparent background instead...?

Thanks again!
Look forward to hearing from you!

**Comment by mansya** [comment]
hello sir. I changed the shape of the design. I prefer this form. this looks interesting and unique to me. What do you think ? do you like it ? if yes. which one you like.
![Calculator java](https://user-images.githubusercontent.com/33461607/58033824-65ad4d80-7b4f-11e9-88c8-78cfb6ba96eb.png)

**Comment by mansya** [comment]
hi sir. how about this offer. don't you want to continue?

**Comment by pH-7** [comment]
Hi @mansya 

So sorry for the delay. The logo "2" is my favorite! I chose that one.
I would be pleased to add it to the project once you provide me the transparent PNG file for that one :)

Thank you! 😊

**Comment by mansya** [comment]
hi sir. I have sent you [**Pull Requests.**](https://github.com/pH-7/Simple-Java-Calculator/pull/16) please check. and I have also uploaded all files to this [**Drive.**](https://drive.google.com/open?id=1RAwGNXHkoclQPm2Z8ZL5pIgBhnGcYxvh)

**Comment by pH-7** [comment]
I reviewed and merged it, @mansya 
I really appreciate it 😄 


Good luck!
