### ISSUE TITLE
showing input == null! on eclipse 

### ISSUE THREAD

**Issue by encarcio** [pH-7/Simple-Java-Calculator#37]
![Capture](https://user-images.githubusercontent.com/32518913/75180025-56ec6a80-5761-11ea-81de-fa0630cb59c7.PNG)

On running the project on eclipse IDE , the above output is showing.

**Comment by lyqheheda** [comment]
I have encountered the same situation. Have you solved it yet?

**Comment by encarcio** [comment]
No haven't solved it yet. Are you taking it?

**Comment by encarcio** [comment]
![Capture](https://user-images.githubusercontent.com/32518913/80858589-bc843800-8c77-11ea-8147-c502348c1d92.PNG)

 I am still getting the same output.

**Comment by encarcio** [comment]
It worked in eclipse.
