### ISSUE TITLE
Simple-java-Calculator


### ISSUE THREAD

**Issue by Socrates-maker** [pH-7/Simple-Java-Calculator#59]

**Comment by xdvrx1** [comment]
just trying this out, right? 

In GitHub, we use issues to ask something, to fix a bug, to reference a pull request, to present errors in the codebase, etc.

please simply close the issue, thanks

**Comment by huzaifansari54** [comment]
hello i am new i want to contribute give me some advise

**Comment by pH-7** [comment]
Off-topic. Closing now :)
