### ISSUE TITLE
Extend SimpleJavaCalculator

### ISSUE THREAD

**Issue by xatza** [pH-7/Simple-Java-Calculator#6]
Hello,
I appreciate your work,i really like your project.
I try to extend your code,so i add three new buttons.
Specifically i add x^y button,which calculates x(first number) power of y(second number).Second button is log10(x),which calculates the logarithm of a number x.Finally i add x% button,which calculates the percentage of the number x.
I also upload the files with changes,so you can check it.
I hope you find it helpful.

Friendly,
Donis Chantzaridis

[simplejavacalculator.zip](https://github.com/pH-7/Simple-Java-Calculator/files/1603306/simplejavacalculator.zip)
![2f4e7b4079cfb65c4c1d7128b06801ae](https://user-images.githubusercontent.com/20843685/34563666-27c31348-f15c-11e7-9fdc-15e6a7d24669.png)

**Comment by pH-7** [comment]
Hi again @xatza!

Thanks for your modifs! Highly appreciate.
However, if you want to add modifications, you should fork the project, commit your changes locally, and then open a pull request. In that way, I can review your changes easily on Github and this is convenient for both of us 😃

**Comment by pH-7** [comment]
FTR, PR has been created here https://github.com/pH-7/Simple-Java-Calculator/pull/8
