### ISSUE TITLE
Request to add new function to the calculator

### ISSUE THREAD

**Issue by jorianCheong** [pH-7/Simple-Java-Calculator#79]
I wish to contribute a inverseSin function to the calculator

**Comment by jorianCheong** [comment]
@pH-7 @achinthagunasekara @hczhcz @xatza

**Comment by pH-7** [comment]
Hey @jorianCheong 👋 I replied to you [on your PR](https://github.com/pH-7/Simple-Java-Calculator/pull/77). Thank you 🙂
