### ISSUE TITLE
Remove private nbproject folder from repository

### ISSUE THREAD

**Issue by opheliagame** [pH-7/Simple-Java-Calculator#9]
There is a folder called private under the nbproject folder. This folder contains private information that is machine specific and not project specific.
According to the following link:
[http://docs.oracle.com/cd/E50453_01/doc.80/e50452/create_japps.htm#NBDAG2974](url)

> If the project is checked out of a version control system, the build (or nbbuild), dist (or nbdist), and the nbproject/private folders should not be checked into that version control system. If the project is under the CVS, Subversion, or Mercurial version control systems, the appropriate "ignore" files are created or updated for these directories when the project is imported. Though nbproject/private should be ignored, nbproject should be checked into the version control system. nbproject contains project metadata that enables other users to open the project in NetBeans without having to import the project first.

**Comment by pH-7** [comment]
Thanks for pointing this. Since you are on it right now, can you create a PR that removes `nbproject/private` (and add it on `.gitignore` file as well to make sure it won't be commited anymore0

**Comment by pH-7** [comment]
Fixed. Thanks @opheliagame!

**Comment by opheliagame** [comment]
The first issue I raised! Happy to help :) @pH-7
