### ISSUE TITLE
Bug Report: Incorrect Use of .equals() Method for Object Comparison

### ISSUE THREAD

**Issue by nabikhalid** [pH-7/Simple-Java-Calculator#97]
**Project:** SimpleJavaCalculator  
**File Affected:** `Calculator.java`  
**Line Number:** [Line number where the bug is found, for example: 57]  
**Severity:** High

**Description:**  
The PMD tool detected an issue in `Calculator.java` related to the incorrect use of the `.equals()` method for object comparison. Using `==` or `!=` for object comparison can lead to unintended behaviors since it checks for reference equality rather than content equality. In Java, when comparing objects for equality in terms of their content, the `.equals()` method should be employed.

**Output from PMD:**  
``` 
[WARNING] PMD violation detected. Rule:UseEqualsToCompareStrings Priority:3 .equals() should be used to compare object references. 
```

**Suggested Fix:**  
Replace the `==` or `!=` comparison of objects with the `.equals()` method for accurate content-based comparison. Ensure that the class has a properly overridden `.equals()` method if needed.

**Steps to Reproduce:**  
1. Navigate to `Calculator.java`.
2. Go to the mentioned line number.
3. Observe the object comparison using `==` or `!=`.

**Additional Notes:**  
This kind of bug can potentially lead to logical errors in the application. Even if the current implementation does not throw an error, it's a potential source of future bugs, especially if changes are made to the way objects are created or managed.

**Comment by pH-7** [comment]
Fixed in https://github.com/pH-7/Simple-Java-Calculator/pull/104
